#![doc = "Peripheral access API for ATSAM3X8E microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
  fn PMC();
  fn EFC0();
  fn EFC1();
  fn UART();
  fn PIOA();
  fn PIOB();
  fn PIOC();
  fn PIOD();
  fn USART0();
  fn USART1();
  fn USART2();
  fn USART3();
  fn HSMCI();
  fn TWI0();
  fn TWI1();
  fn SPI0();
  fn SSC();
  fn TC0();
  fn TC1();
  fn TC2();
  fn TC3();
  fn TC4();
  fn TC5();
  fn TC6();
  fn TC7();
  fn TC8();
  fn PWM();
  fn ADC();
  fn DACC();
  fn DMAC();
  fn UOTGHS();
  fn TRNG();
  fn EMAC();
  fn CAN0();
  fn CAN1();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
  _handler: unsafe extern "C" fn(),
  _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 45] = [
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _handler: PMC },
  Vector { _handler: EFC0 },
  Vector { _handler: EFC1 },
  Vector { _handler: UART },
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _handler: PIOA },
  Vector { _handler: PIOB },
  Vector { _handler: PIOC },
  Vector { _handler: PIOD },
  Vector { _reserved: 0 },
  Vector { _reserved: 0 },
  Vector { _handler: USART0 },
  Vector { _handler: USART1 },
  Vector { _handler: USART2 },
  Vector { _handler: USART3 },
  Vector { _handler: HSMCI },
  Vector { _handler: TWI0 },
  Vector { _handler: TWI1 },
  Vector { _handler: SPI0 },
  Vector { _reserved: 0 },
  Vector { _handler: SSC },
  Vector { _handler: TC0 },
  Vector { _handler: TC1 },
  Vector { _handler: TC2 },
  Vector { _handler: TC3 },
  Vector { _handler: TC4 },
  Vector { _handler: TC5 },
  Vector { _handler: TC6 },
  Vector { _handler: TC7 },
  Vector { _handler: TC8 },
  Vector { _handler: PWM },
  Vector { _handler: ADC },
  Vector { _handler: DACC },
  Vector { _handler: DMAC },
  Vector { _handler: UOTGHS },
  Vector { _handler: TRNG },
  Vector { _handler: EMAC },
  Vector { _handler: CAN0 },
  Vector { _handler: CAN1 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
  #[doc = "5 - PMC"]
  PMC = 5,
  #[doc = "6 - EFC0"]
  EFC0 = 6,
  #[doc = "7 - EFC1"]
  EFC1 = 7,
  #[doc = "8 - UART"]
  UART = 8,
  #[doc = "11 - PIOA"]
  PIOA = 11,
  #[doc = "12 - PIOB"]
  PIOB = 12,
  #[doc = "13 - PIOC"]
  PIOC = 13,
  #[doc = "14 - PIOD"]
  PIOD = 14,
  #[doc = "17 - USART0"]
  USART0 = 17,
  #[doc = "18 - USART1"]
  USART1 = 18,
  #[doc = "19 - USART2"]
  USART2 = 19,
  #[doc = "20 - USART3"]
  USART3 = 20,
  #[doc = "21 - HSMCI"]
  HSMCI = 21,
  #[doc = "22 - TWI0"]
  TWI0 = 22,
  #[doc = "23 - TWI1"]
  TWI1 = 23,
  #[doc = "24 - SPI0"]
  SPI0 = 24,
  #[doc = "26 - SSC"]
  SSC = 26,
  #[doc = "27 - TC0"]
  TC0 = 27,
  #[doc = "28 - TC1"]
  TC1 = 28,
  #[doc = "29 - TC2"]
  TC2 = 29,
  #[doc = "30 - TC3"]
  TC3 = 30,
  #[doc = "31 - TC4"]
  TC4 = 31,
  #[doc = "32 - TC5"]
  TC5 = 32,
  #[doc = "33 - TC6"]
  TC6 = 33,
  #[doc = "34 - TC7"]
  TC7 = 34,
  #[doc = "35 - TC8"]
  TC8 = 35,
  #[doc = "36 - PWM"]
  PWM = 36,
  #[doc = "37 - ADC"]
  ADC = 37,
  #[doc = "38 - DACC"]
  DACC = 38,
  #[doc = "39 - DMAC"]
  DMAC = 39,
  #[doc = "40 - UOTGHS"]
  UOTGHS = 40,
  #[doc = "41 - TRNG"]
  TRNG = 41,
  #[doc = "42 - EMAC"]
  EMAC = 42,
  #[doc = "43 - CAN0"]
  CAN0 = 43,
  #[doc = "44 - CAN1"]
  CAN1 = 44,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
  #[inline(always)]
  fn number(self) -> u16 {
    self as u16
  }
}
#[doc = "High Speed MultiMedia Card Interface"]
pub type Hsmci = crate::Periph<hsmci::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Hsmci {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Hsmci").finish()
  }
}
#[doc = "High Speed MultiMedia Card Interface"]
pub mod hsmci;
#[doc = "Synchronous Serial Controller"]
pub type Ssc = crate::Periph<ssc::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Ssc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Ssc").finish()
  }
}
#[doc = "Synchronous Serial Controller"]
pub mod ssc;
#[doc = "Serial Peripheral Interface 0"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Spi0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Spi0").finish()
  }
}
#[doc = "Serial Peripheral Interface 0"]
pub mod spi0;
#[doc = "Timer Counter 0"]
pub type Tc0 = crate::Periph<tc0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Tc0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Tc0").finish()
  }
}
#[doc = "Timer Counter 0"]
pub mod tc0;
#[doc = "Timer Counter 1"]
pub type Tc1 = crate::Periph<tc1::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Tc1 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Tc1").finish()
  }
}
#[doc = "Timer Counter 1"]
pub mod tc1;
#[doc = "Timer Counter 2"]
pub type Tc2 = crate::Periph<tc2::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Tc2 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Tc2").finish()
  }
}
#[doc = "Timer Counter 2"]
pub mod tc2;
#[doc = "Two-wire Interface 0"]
pub type Twi0 = crate::Periph<twi0::RegisterBlock, 0x4008_c000>;
impl core::fmt::Debug for Twi0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Twi0").finish()
  }
}
#[doc = "Two-wire Interface 0"]
pub mod twi0;
#[doc = "Two-wire Interface 1"]
pub type Twi1 = crate::Periph<twi1::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for Twi1 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Twi1").finish()
  }
}
#[doc = "Two-wire Interface 1"]
pub mod twi1;
#[doc = "Pulse Width Modulation Controller"]
pub type Pwm = crate::Periph<pwm::RegisterBlock, 0x4009_4000>;
impl core::fmt::Debug for Pwm {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Pwm").finish()
  }
}
#[doc = "Pulse Width Modulation Controller"]
pub mod pwm;
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 0"]
pub type Usart0 = crate::Periph<usart0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for Usart0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Usart0").finish()
  }
}
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 0"]
pub mod usart0;
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 1"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4009_c000>;
impl core::fmt::Debug for Usart1 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Usart1").finish()
  }
}
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 1"]
pub mod usart1;
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 2"]
pub type Usart2 = crate::Periph<usart2::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for Usart2 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Usart2").finish()
  }
}
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 2"]
pub mod usart2;
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 3"]
pub type Usart3 = crate::Periph<usart3::RegisterBlock, 0x400a_4000>;
impl core::fmt::Debug for Usart3 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Usart3").finish()
  }
}
#[doc = "Universal Synchronous Asynchronous Receiver Transmitter 3"]
pub mod usart3;
#[doc = "USB On-The-Go Interface"]
pub type Uotghs = crate::Periph<uotghs::RegisterBlock, 0x400a_c000>;
impl core::fmt::Debug for Uotghs {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Uotghs").finish()
  }
}
#[doc = "USB On-The-Go Interface"]
pub mod uotghs;
#[doc = "Ethernet MAC 10/100"]
pub type Emac = crate::Periph<emac::RegisterBlock, 0x400b_0000>;
impl core::fmt::Debug for Emac {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Emac").finish()
  }
}
#[doc = "Ethernet MAC 10/100"]
pub mod emac;
#[doc = "Controller Area Network 0"]
pub type Can0 = crate::Periph<can0::RegisterBlock, 0x400b_4000>;
impl core::fmt::Debug for Can0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Can0").finish()
  }
}
#[doc = "Controller Area Network 0"]
pub mod can0;
#[doc = "Controller Area Network 1"]
pub type Can1 = crate::Periph<can1::RegisterBlock, 0x400b_8000>;
impl core::fmt::Debug for Can1 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Can1").finish()
  }
}
#[doc = "Controller Area Network 1"]
pub mod can1;
#[doc = "True Random Number Generator"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x400b_c000>;
impl core::fmt::Debug for Trng {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Trng").finish()
  }
}
#[doc = "True Random Number Generator"]
pub mod trng;
#[doc = "Analog-to-Digital Converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x400c_0000>;
impl core::fmt::Debug for Adc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Adc").finish()
  }
}
#[doc = "Analog-to-Digital Converter"]
pub mod adc;
#[doc = "DMA Controller"]
pub type Dmac = crate::Periph<dmac::RegisterBlock, 0x400c_4000>;
impl core::fmt::Debug for Dmac {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Dmac").finish()
  }
}
#[doc = "DMA Controller"]
pub mod dmac;
#[doc = "Digital-to-Analog Converter Controller"]
pub type Dacc = crate::Periph<dacc::RegisterBlock, 0x400c_8000>;
impl core::fmt::Debug for Dacc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Dacc").finish()
  }
}
#[doc = "Digital-to-Analog Converter Controller"]
pub mod dacc;
#[doc = "Static Memory Controller"]
pub type Smc = crate::Periph<smc::RegisterBlock, 0x400e_0000>;
impl core::fmt::Debug for Smc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Smc").finish()
  }
}
#[doc = "Static Memory Controller"]
pub mod smc;
#[doc = "AHB Bus Matrix"]
pub type Matrix = crate::Periph<matrix::RegisterBlock, 0x400e_0400>;
impl core::fmt::Debug for Matrix {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Matrix").finish()
  }
}
#[doc = "AHB Bus Matrix"]
pub mod matrix;
#[doc = "Power Management Controller"]
pub type Pmc = crate::Periph<pmc::RegisterBlock, 0x400e_0600>;
impl core::fmt::Debug for Pmc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Pmc").finish()
  }
}
#[doc = "Power Management Controller"]
pub mod pmc;
#[doc = "Universal Asynchronous Receiver Transmitter"]
pub type Uart = crate::Periph<uart::RegisterBlock, 0x400e_0800>;
impl core::fmt::Debug for Uart {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Uart").finish()
  }
}
#[doc = "Universal Asynchronous Receiver Transmitter"]
pub mod uart;
#[doc = "Chip Identifier"]
pub type Chipid = crate::Periph<chipid::RegisterBlock, 0x400e_0940>;
impl core::fmt::Debug for Chipid {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Chipid").finish()
  }
}
#[doc = "Chip Identifier"]
pub mod chipid;
#[doc = "Embedded Flash Controller 0"]
pub type Efc0 = crate::Periph<efc0::RegisterBlock, 0x400e_0a00>;
impl core::fmt::Debug for Efc0 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Efc0").finish()
  }
}
#[doc = "Embedded Flash Controller 0"]
pub mod efc0;
#[doc = "Embedded Flash Controller 1"]
pub type Efc1 = crate::Periph<efc1::RegisterBlock, 0x400e_0c00>;
impl core::fmt::Debug for Efc1 {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Efc1").finish()
  }
}
#[doc = "Embedded Flash Controller 1"]
pub mod efc1;
#[doc = "Parallel Input/Output Controller A"]
pub type Pioa = crate::Periph<pioa::RegisterBlock, 0x400e_0e00>;
impl core::fmt::Debug for Pioa {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Pioa").finish()
  }
}
#[doc = "Parallel Input/Output Controller A"]
pub mod pioa;
#[doc = "Parallel Input/Output Controller B"]
pub type Piob = crate::Periph<piob::RegisterBlock, 0x400e_1000>;
impl core::fmt::Debug for Piob {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Piob").finish()
  }
}
#[doc = "Parallel Input/Output Controller B"]
pub mod piob;
#[doc = "Parallel Input/Output Controller C"]
pub type Pioc = crate::Periph<pioc::RegisterBlock, 0x400e_1200>;
impl core::fmt::Debug for Pioc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Pioc").finish()
  }
}
#[doc = "Parallel Input/Output Controller C"]
pub mod pioc;
#[doc = "Parallel Input/Output Controller D"]
pub type Piod = crate::Periph<piod::RegisterBlock, 0x400e_1400>;
impl core::fmt::Debug for Piod {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Piod").finish()
  }
}
#[doc = "Parallel Input/Output Controller D"]
pub mod piod;
#[doc = "Reset Controller"]
pub type Rstc = crate::Periph<rstc::RegisterBlock, 0x400e_1a00>;
impl core::fmt::Debug for Rstc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Rstc").finish()
  }
}
#[doc = "Reset Controller"]
pub mod rstc;
#[doc = "Supply Controller"]
pub type Supc = crate::Periph<supc::RegisterBlock, 0x400e_1a10>;
impl core::fmt::Debug for Supc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Supc").finish()
  }
}
#[doc = "Supply Controller"]
pub mod supc;
#[doc = "Real-time Timer"]
pub type Rtt = crate::Periph<rtt::RegisterBlock, 0x400e_1a30>;
impl core::fmt::Debug for Rtt {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Rtt").finish()
  }
}
#[doc = "Real-time Timer"]
pub mod rtt;
#[doc = "Watchdog Timer"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x400e_1a50>;
impl core::fmt::Debug for Wdt {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Wdt").finish()
  }
}
#[doc = "Watchdog Timer"]
pub mod wdt;
#[doc = "Real-time Clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x400e_1a60>;
impl core::fmt::Debug for Rtc {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Rtc").finish()
  }
}
#[doc = "Real-time Clock"]
pub mod rtc;
#[doc = "General Purpose Backup Register"]
pub type Gpbr = crate::Periph<gpbr::RegisterBlock, 0x400e_1a90>;
impl core::fmt::Debug for Gpbr {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Gpbr").finish()
  }
}
#[doc = "General Purpose Backup Register"]
pub mod gpbr;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
  #[doc = "HSMCI"]
  pub hsmci: Hsmci,
  #[doc = "SSC"]
  pub ssc: Ssc,
  #[doc = "SPI0"]
  pub spi0: Spi0,
  #[doc = "TC0"]
  pub tc0: Tc0,
  #[doc = "TC1"]
  pub tc1: Tc1,
  #[doc = "TC2"]
  pub tc2: Tc2,
  #[doc = "TWI0"]
  pub twi0: Twi0,
  #[doc = "TWI1"]
  pub twi1: Twi1,
  #[doc = "PWM"]
  pub pwm: Pwm,
  #[doc = "USART0"]
  pub usart0: Usart0,
  #[doc = "USART1"]
  pub usart1: Usart1,
  #[doc = "USART2"]
  pub usart2: Usart2,
  #[doc = "USART3"]
  pub usart3: Usart3,
  #[doc = "UOTGHS"]
  pub uotghs: Uotghs,
  #[doc = "EMAC"]
  pub emac: Emac,
  #[doc = "CAN0"]
  pub can0: Can0,
  #[doc = "CAN1"]
  pub can1: Can1,
  #[doc = "TRNG"]
  pub trng: Trng,
  #[doc = "ADC"]
  pub adc: Adc,
  #[doc = "DMAC"]
  pub dmac: Dmac,
  #[doc = "DACC"]
  pub dacc: Dacc,
  #[doc = "SMC"]
  pub smc: Smc,
  #[doc = "MATRIX"]
  pub matrix: Matrix,
  #[doc = "PMC"]
  pub pmc: Pmc,
  #[doc = "UART"]
  pub uart: Uart,
  #[doc = "CHIPID"]
  pub chipid: Chipid,
  #[doc = "EFC0"]
  pub efc0: Efc0,
  #[doc = "EFC1"]
  pub efc1: Efc1,
  #[doc = "PIOA"]
  pub pioa: Pioa,
  #[doc = "PIOB"]
  pub piob: Piob,
  #[doc = "PIOC"]
  pub pioc: Pioc,
  #[doc = "PIOD"]
  pub piod: Piod,
  #[doc = "RSTC"]
  pub rstc: Rstc,
  #[doc = "SUPC"]
  pub supc: Supc,
  #[doc = "RTT"]
  pub rtt: Rtt,
  #[doc = "WDT"]
  pub wdt: Wdt,
  #[doc = "RTC"]
  pub rtc: Rtc,
  #[doc = "GPBR"]
  pub gpbr: Gpbr,
}
impl Peripherals {
  #[doc = r" Returns all the peripherals *once*."]
  #[cfg(feature = "critical-section")]
  #[inline]
  pub fn take() -> Option<Self> {
    critical_section::with(|_| {
      if unsafe { DEVICE_PERIPHERALS } {
        return None;
      }
      Some(unsafe { Peripherals::steal() })
    })
  }
  #[doc = r" Unchecked version of `Peripherals::take`."]
  #[doc = r""]
  #[doc = r" # Safety"]
  #[doc = r""]
  #[doc = r" Each of the returned peripherals must be used at most once."]
  #[inline]
  pub unsafe fn steal() -> Self {
    DEVICE_PERIPHERALS = true;
    Peripherals {
      hsmci: unsafe { Hsmci::steal() },
      ssc: unsafe { Ssc::steal() },
      spi0: unsafe { Spi0::steal() },
      tc0: unsafe { Tc0::steal() },
      tc1: unsafe { Tc1::steal() },
      tc2: unsafe { Tc2::steal() },
      twi0: unsafe { Twi0::steal() },
      twi1: unsafe { Twi1::steal() },
      pwm: unsafe { Pwm::steal() },
      usart0: unsafe { Usart0::steal() },
      usart1: unsafe { Usart1::steal() },
      usart2: unsafe { Usart2::steal() },
      usart3: unsafe { Usart3::steal() },
      uotghs: unsafe { Uotghs::steal() },
      emac: unsafe { Emac::steal() },
      can0: unsafe { Can0::steal() },
      can1: unsafe { Can1::steal() },
      trng: unsafe { Trng::steal() },
      adc: unsafe { Adc::steal() },
      dmac: unsafe { Dmac::steal() },
      dacc: unsafe { Dacc::steal() },
      smc: unsafe { Smc::steal() },
      matrix: unsafe { Matrix::steal() },
      pmc: unsafe { Pmc::steal() },
      uart: unsafe { Uart::steal() },
      chipid: unsafe { Chipid::steal() },
      efc0: unsafe { Efc0::steal() },
      efc1: unsafe { Efc1::steal() },
      pioa: unsafe { Pioa::steal() },
      piob: unsafe { Piob::steal() },
      pioc: unsafe { Pioc::steal() },
      piod: unsafe { Piod::steal() },
      rstc: unsafe { Rstc::steal() },
      supc: unsafe { Supc::steal() },
      rtt: unsafe { Rtt::steal() },
      wdt: unsafe { Wdt::steal() },
      rtc: unsafe { Rtc::steal() },
      gpbr: unsafe { Gpbr::steal() },
    }
  }
}
